### ISSUE TITLE
Chained futures can hold the lock too long

### ISSUE THREAD

**Issue by asomers** [asomers/futures-locks#3]
Tokio guarantees that it will promptly poll each task upon readiness notification.  However, it does not guarantee that it will promptly poll all of a task's futures.  This can lead to situations where a `MutexFut` may gain ownership of its resource, but never get polled because some other Future in its task isn't ready yet.  For example, in the below snippet, the `MutexFut` could gain ownership of its `Mutex`, but its continuation won't run if the socket is not ready to send.

```rust
socket.send_all(
    stream.map(|_| {
        mutex.lock().and_then(|guard| do_something_async_but_fast)
    })
)
```

When using Tokio, latency-sensitive operations are best done in their own tasks.  `futures-locks` should add some helper methods to make this easy, for both `Mutex` and `RwLock`.

Reported-by: @carllerche, @diggsey

**Comment by Diggsey** [comment]
It's a bit weird that this feature depends on tokio? The methods should take a handle to an executor as an argument, or use their own executor.

Also, I wouldn't consider this fixed whilst the original methods are neither deprecated nor have a big warning: increased latency is not really the problem, it's that there's nothing driving the mutex to be unlocked, and so their's a high propensity for deadlocks. Particularly when this issue is so subtle and hard to grasp.

If you're using a buffered channel instead of a socket for example, and the channel gets full then the sender might never release the lock (since it's never able to complete its send operation) and the receiver will never be able to take the lock, and so will not clear any space in the channel.

**Comment by asomers** [comment]
It depends on Tokio because plain futures doesn't know how to spawn a Tokio task.  Or at least, I couldn't find any documentation that indicated that it does.  Do you know something that I don't?  And if it can't, then there's no good way to improve the original `lock` method.  I don't want to do anything as expensive as create a new thread.
