### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by jplatte** [asomers/futures-locks#44]
Given #37 has not received any feedback, I'm wondering if this library is still maintained. If yes, would you be open to a PR that replaces the `futures` dependency with dependencies on the individual `futures-*` crates that are actually needed?

**Comment by asomers** [comment]
Yes, it is maintained, as needs arise.  However, it is no longer as important as it used to be, since tokio-1.0 now has its own locks implementation in https://docs.rs/tokio/1.13.0/tokio/sync/index.html .  The APIs aren't identical, but they're close, and I would recommend tokio::sync for most new applications.  Issue #37 must've slipped through my radar.

**Comment by jplatte** [comment]
The issue with tokio is that it doesn't work on wasm as well, so it's good to have this as an alternative. I'll create a PR for the dependency improvement.
